<?xml version="1.0" encoding="utf-8"?><Database Name="EmployeeSample" Class="EmployeesDatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=CORSAIR-DB\SQLSERVER2014;Initial Catalog=EmployeeSample;Integrated Security=True" SettingsObjectName="C_Sharp_Examples.Properties.Settings" SettingsPropertyName="EmployeeSampleConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Employees" Member="Employees">
    <Type Name="Employee">
      <Column Name="EmployeeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="JobDescriptionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="JobDescription_Employee" Member="JobDescription" ThisKey="JobDescriptionId" OtherKey="JobDescriptionId" Type="JobDescription" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.JobDescriptions" Member="JobDescriptions">
    <Type Name="JobDescription">
      <Column Name="JobDescriptionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="JobDescription" Member="JobDescription1" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="JobDescription_Employee" Member="Employees" ThisKey="JobDescriptionId" OtherKey="JobDescriptionId" Type="Employee" />
    </Type>
  </Table>
</Database>